version: '3'

services:
  wordpress:
    build:
      context: ./dev-ops/.
      args:
        XDEBUG: false
        PRODUCTION: false
    ports:
      - '${WORDPRESS_PORT}:8080'
    env_file: .env
    volumes:
      - ./:/var/www/html/wp-content/themes/demo-theme
        
  testdatabase:
    image: mariadb:10.2
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_USER=${TEST_DB_USER}
      - MARIADB_PASSWORD=${TEST_DB_PASSWORD}
      - MARIADB_DATABASE=${TEST_DB_NAME}
    healthcheck: 
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MARIADB_ROOT_PASSWORD
      interval: 30s
      retries: 10
